### ISSUE TITLE
why the minisdk is 15?

### ISSUE THREAD

**Issue by a1018875550** [SwiftyWang/ToastBar#3]
why?

**Comment by SwiftyWang** [comment]
This one is just for my internal app before, but haven't change the gradle configuration.

**Comment by a1018875550** [comment]
Could this change the minisdk for 14?

**Comment by SwiftyWang** [comment]
Yeah, I will change it tonight or u can change it and PR the changes.

**Comment by SwiftyWang** [comment]
Has updated to min sdk 14. Plz use 1.1.4 version.
