### ISSUE TITLE
如何调用setBackgroundColor方法呢？

### ISSUE THREAD

**Issue by lv910929** [SwiftyWang/ToastBar#4]
demo里面没有给出啊，链式写法也不支持，该不如调用啊？ @SwiftyWang

**Comment by SwiftyWang** [comment]
Have u try  Toptoast.make(...).setBackground().show() ?

lv910929 <notifications@github.com>于2016年11月30日周三 08:50写道：

**Comment by lv910929** [comment]
thanks,it work
