### ISSUE TITLE
com.swifty.toptoastbar.FloatWindowService (has extras) }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@368bf1b1 -- permission denied for this window type

### ISSUE THREAD

**Issue by wushangjun** [SwiftyWang/ToastBar#8]
com.swifty.toptoastbar.FloatWindowService (has extras) }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@368bf1b1 -- permission denied for this window type

**Comment by SwiftyWang** [comment]
fixed in 1.1.6 release 665531fa5495c9189111047fc19f55dcfc492159
